server:
  port: 8081

spring:
  application:
    name: WELCOME-API

  boot:
    admin:
      client:
        url: http://localhost:1111/

#this is option, If eureka server is running on 8761 then no need to give the below the property, if not you need
# to mention the below property.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

managment:
  endpoints:
    web:
      exposure:
        include: '*'

